### ISSUE TITLE
Update highways to include opposite highwayid.

### ISSUE THREAD

**Issue by joshproehl** [Routelandia/routelandia-server#82]
This field should be available on production. Needs to me added to staging, and have the entity updated to include this value in the output JSON.

**Comment by severity** [comment]
@joshproehl: I could probably do this, at least the entity modification, what needs to be added to staging?

**Comment by joshproehl** [comment]
We need to copy the new highways table from the production server to the staging server so that we can base the code off of the correct table..

**Comment by severity** [comment]
ha ha, thats probably outside of my abilities but I can modify the entities when its done :D

**Comment by pgicking** [comment]
pgicking [11:34 AM] 
ok i can do it

pgicking [11:34 AM]
but i want to do it the lazy way

pgicking [11:35 AM]
and just drop highways and the view thats dependant on it

pgicking [11:35 AM]
and just paste in the new table

pgicking [11:35 AM]
and new view

pgicking [11:35 AM]
which would break the app for a bit

**Comment by joshproehl** [comment]
Since this is non-breaking once you add the new table, it means we'll still be able to do a demo tonight if we need to do a live one, so as long as you get the table back where it's supposed to be I say go for it. ;-)

**Comment by pgicking** [comment]
alright, should be good now

**Comment by joshproehl** [comment]
Hah, I forgot that we don't actually need to DO anything once the column is appearing in the table... Respect/Relational did it for us. ;-)
@severity is off the hook!
